Created foundation files for the student components
peyton-lalli/swe5-project-frontend pull request #3
Opened 2023-02-10 15:16 UTC by LoganDemaray316

Created Files:
EventsItem.vue
QuickLinksComponent.vue
RecentCritiquesComponent.vue
RecentItem.vue
RepertoireComponent.vue
RepertoireItem.vue
YourEventsComponent.vue

Altered Files:
App.vue
StudentHomeDashboard.vue

Added Images:
Unknown.jpeg

This creates the foundation for the student home page for where all information should be placed in rows and columns inside v-card.

2023-02-11 17:31 UTC, ethanimooney requested changes

2023-02-11 17:31 UTC, ethanimooney commented on src/App.vue
> +    <v-container fill-height>
If you add fluid back here, it will make the container fill the whole width of the screen too.

2023-02-11 17:31 UTC, ethanimooney commented on src/components/RecentCritiquesComponent.vue
> +  export default {
Go ahead and add this section with at least just the name, data and methods section just to make them even and make our time later easier.

2023-02-11 17:31 UTC, ethanimooney commented on src/components/RepertoireComponent.vue
> +<template>
This doesn't need to be a component - just a list in the repertoire section of the home dashboard. So I would get rid of this and just add one of the RepertoireItemComponents to the StudentHomeDashboard for now. 

We'll do like a v-for on a list of repertoire items to fill the repertoire section once we have actual data.

2023-02-11 17:31 UTC, ethanimooney commented on src/components/YourEventsComponent.vue
> +<template>
Same thing here as with the repertoire - this doesn't need to be a component, all we need is a list of EventsItemComponent in the events section on the StudentHomeDashboard.

2023-02-11 23:03 UTC, LoganDemaray316 commented on src/App.vue
> +    <v-container fill-height>
This did not do anything, but it is back in.

2023-02-11 23:18 UTC, LoganDemaray316 commented on src/components/RecentCritiquesComponent.vue
> +  export default {
Fixed

2023-02-11 23:18 UTC, LoganDemaray316 commented on src/components/RepertoireComponent.vue
> +<template>
Fixed

2023-02-11 23:18 UTC, LoganDemaray316 commented on src/components/YourEventsComponent.vue
> +<template>
Fixed

2023-02-12 00:29 UTC, ethanimooney approved these changes
LGTM

2023-02-12 00:31 UTC, merged